#!/usr/bin/python

import os
import sys
import yaml


def dub_test():
    print("dub test --compiler=$DC")
    sys.exit(0)


if not os.path.isfile('.travis.yml'):
    dub_test()

script = yaml.load(open('.travis.yml', 'r')).get('script', '')

if isinstance(script, list):
    script = '\n'.join(script)

if len(script) > 0:
    print(script)
else:
    dub_test()
