---
- name: install mongodb-3.4 apt key
  apt_key: { keyserver: keyserver.ubuntu.com, id: 0C49F3730359A14518585931BC711F9BA15703C6 }
- name: add mongodb-3.4 repo
  apt_repository: { repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse' }
- name: install dependencies
  apt: { name: "{{ item }}", install_recommends: no, update_cache: yes, cache_valid_time: 3600 }
  with_items: [mongodb-org-server=3.4.*, libevent-dev, libssl-dev]
- name: configure mongod
  copy: { src: mongod.conf, dest: /etc/mongod.conf }
  notify: [enable mongod, restart mongod]
- name: start mongodb
  meta: flush_handlers

- name: install dmd
  apt:
    deb: 'https://downloads.dlang.org/releases/2.x/2.083.1/dmd_2.083.1-0_amd64.deb'
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
- name: create registry user
  user: { name: dub-registry }
- name: get dub-registry
  unarchive:
    remote_src: yes
    src: 'https://github.com/dlang/dub-registry/archive/{{ dub_registry_version }}.tar.gz'
    dest: /home/dub-registry
    owner: dub-registry
    group: dub-registry
- name: symlink dub-registry
  file:
    dest: /home/dub-registry/dub-registry
    src: "/home/dub-registry/dub-registry-{{ dub_registry_version | regex_replace('^v(\\d+\\.\\d+\\.\\d+)', '\\1') }}"
    state: link
- name: build dub-registry
  # use single-file build mode for low-mem servers
  command: dub build --build=release --build-mode=singleFile --override-config vibe-d:tls/openssl-1.1
  args:
    chdir: /home/dub-registry/dub-registry
  become_user: dub-registry
  register: build
  changed_when: not build.stdout | search('dub-registry.*up to date')
  tags: rebuild
  notify: restart dub-registry-mirror
- name: install service file
  template: { src: dub-registry-mirror.service.j2, dest: /etc/systemd/system/dub-registry-mirror.service }
  notify: [systemctl daemon-reload, enable dub-registry-mirror, restart dub-registry-mirror]
